-- 步骤类型: N/A, 步骤名称: 同业借贷发生额信息_DM插入
-- 标签: name, 属性: {}, 内容: 同业借贷发生额信息_DM插入
-- 标签: type, 属性: {}, 内容: TableOutput
-- 标签: description, 属性: {}, 内容: None
-- 标签: distribute, 属性: {}, 内容: Y
-- 标签: copies, 属性: {}, 内容: 1
-- 标签: partitioning, 属性: {}, 内容: 
           
-- 标签: connection, 属性: {}, 内容: nstc/jdbc/DmData
-- 标签: schema, 属性: {}, 内容: None
-- 标签: table, 属性: {}, 内容: DM_RFBS_TYJDFS
-- 标签: commit, 属性: {}, 内容: 1000
-- 标签: truncate, 属性: {}, 内容: N
-- 标签: ignore_errors, 属性: {}, 内容: N
-- 标签: use_batch, 属性: {}, 内容: Y
-- 标签: specify_fields, 属性: {}, 内容: N
-- 标签: partitioning_enabled, 属性: {}, 内容: N
-- 标签: partitioning_field, 属性: {}, 内容: None
-- 标签: partitioning_daily, 属性: {}, 内容: N
-- 标签: partitioning_monthly, 属性: {}, 内容: Y
-- 标签: tablename_in_field, 属性: {}, 内容: N
-- 标签: tablename_field, 属性: {}, 内容: None
-- 标签: tablename_in_table, 属性: {}, 内容: Y
-- 标签: return_keys, 属性: {}, 内容: N
-- 标签: return_field, 属性: {}, 内容: None
-- 标签: fields, 属性: {}, 内容: 
    
-- 标签: cluster_schema, 属性: {}, 内容: None
-- 标签: remotesteps, 属性: {}, 内容:    
-- 标签: GUI, 属性: {}, 内容: 
      
