-- 步骤类型: N/A, 步骤名称: 增加序列
-- 标签: name, 属性: {}, 内容: 增加序列
-- 标签: type, 属性: {}, 内容: Sequence
-- 标签: description, 属性: {}, 内容: None
-- 标签: distribute, 属性: {}, 内容: Y
-- 标签: copies, 属性: {}, 内容: 1
-- 标签: partitioning, 属性: {}, 内容: 
           
-- 标签: valuename, 属性: {}, 内容: ID
-- 标签: use_database, 属性: {}, 内容: Y
-- 标签: connection, 属性: {}, 内容: nstc/jdbc/DmData
-- 标签: schema, 属性: {}, 内容: None
-- 标签: seqname, 属性: {}, 内容: SEQ_DM_RFBS_CLPJRZ
-- 标签: use_counter, 属性: {}, 内容: N
-- 标签: counter_name, 属性: {}, 内容: None
-- 标签: start_at, 属性: {}, 内容: 1
-- 标签: increment_by, 属性: {}, 内容: 1
-- 标签: max_value, 属性: {}, 内容: 999999999
-- 标签: cluster_schema, 属性: {}, 内容: None
-- 标签: remotesteps, 属性: {}, 内容:    
-- 标签: GUI, 属性: {}, 内容: 
      
